### ISSUE TITLE
Write build script for ARM devices such as Raspberry Pi.

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-native#50]
Current build script does not support ARM architecture except Android. Currently supported platforms are Android, Windows, Linux and OSX. Need to figure out how to build couchbase-lite-java-native for arm architecture such as Raspberry Pi.

**Comment by nraboy** [comment]
+1

Raspberry Pi and IoT are becoming increasingly important.  Couchbase definitely needs to be supported on the ARM architecture via the Java SDK.

cc @HodGreeley @tleyden @arun-gupta

**Comment by twelvearrays** [comment]
My team is trying to build a current Couchbase lite java 1.3.1 version on the Raspberry Pi for our current Point-of-Sale project.  We are currently running version Couchbase lite java 1.1 from a previous build we found on pi on couch.  We use the pi as a print queue to handle all of our printing from our iPads.  This works very well, but we are concerned about how far the versions are apart now.  We would love to help and test if someone can point us in the right direction.

**Comment by hideki** [comment]
Hi @twelvearrays,

You could be latest native library with using following branch.
https://github.com/couchbase/couchbase-lite-java-native/tree/raspi

Thanks,
Hideki

**Comment by twelvearrays** [comment]
Thanks! We have it built now!

**Comment by nemanjanedic** [comment]
Hi all,

is there any chance that this will be merged to master and released in the near future?

Regards,
Nemanja

**Comment by iamchathu** [comment]
I'm using raspi branch and I got an error when I run ./gradlew -Pspec=cross

```bash
FAILURE: Build failed with an exception.

*Where
Script 'home/pi/Downloads/couchbase-lite-java-native-master/sqlite-custom/build-cross.gradle' line: 136

*What went wrong:
A problem occurred evaluating script.
> Could not find property 'binaries' on root project 'sqlite-custom'.

```

I have downloaded the master branch and add build-cross.grade to sqlite-custom folder and manually added `/vendor/sqlite/libs/linux/arm/libsqlite3.a` file and `vendor/sqlite/libs/linux/arm/libsqlite3.so` going through commits in raspi branch.

**Comment by iamchathu** [comment]
I got fix the error after editing the `build.gradle` inside `sqlite`

After building binaries how to set them in the path?

**Comment by hideki** [comment]
@iamchathu,
you need to add compiled native libraries into `couchbase-lite-java-sqlite-custom-x.x.x.jar` by `jar uf jar-file input-file(s)` (https://docs.oracle.com/javase/tutorial/deployment/jar/update.html)

**Comment by iamchathu** [comment]
Where is the my compiled binaries resides. I couldn't find the file path of distribution. Thank you

**Comment by hideki** [comment]
@iamchathu 
If you build native library with gradle, you could find JAR file under build directory. File name could be classes.jar?

**Comment by iamchathu** [comment]
I have build using command `./gradle Pspec=cross` inside sqlite-custom. I get `BUILD SUCCESSFUL` but there is no build folder inside it 😢

**Comment by hideki** [comment]
if you build at `./couchbase-lite-java-native/sqlite-custom`, `./couchbase-lite-java-native/sqlite-custom/build/libs/couchbase-lite-java-sqlite-custom.jar` should be generated. please confirm.

**Comment by iamchathu** [comment]
I have build it on `home/pi/Downloads/couchbase-lite-java-native-master/sqlite-custom/`, and it says build successful but there is no build folder in `home/pi/Downloads/couchbase-lite-java-native-master/sqlite-custom/build`

**Comment by d122y** [comment]
Old thread, but I thought I'd jump in for the benefit of people who come across it.
wrt @iamchathu post - I think the `build` instruction is missing in the command, should be `./gradlew build -Pspec=cross`

With that I got release-1.4 cross-compiled and updated the jar with
`jar uf ./couchbase-lite-java-sqlite-custom-1.4.0.jar native/linux/arm/libsqlite3.so`
`jar uf ./couchbase-lite-java-sqlite-custom-1.4.0.jar native/linux/arm/libcbljavasqlitecustom.so`

but then got stuck on the exception below. I'm not too experienced in cross-compilation and would appreciate any hint. I'm trying to get it running on a stripped-off custom linux imx6 distro on advantech ROM-7421 board (arm7l)

> SEVERE: Database: Cannot load native library
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeOpen(Ljava/lang/String;ILjava/lang/String;ZZ)J
        at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:194)
        at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:178)
        at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:461)
        at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:191)
        at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:183)
        at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:820)
        at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:803)
        at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:698)
        at com.couchbase.lite.storage.SQLiteStorageEngineBase.open(SQLiteStorageEngineBase.java:70)
        at com.couchbase.lite.store.SQLiteStore.open(SQLiteStore.java:188)
        at com.couchbase.lite.Database.open(Database.java:1345)
        at com.couchbase.lite.Manager.openDatabase(Manager.java:341)
        at com.couchbase.lite.Manager.getDatabase(Manager.java:305)
        at Main.main(Main.java:33)

I've run readelf -d for libsqliter3.so and for libcbljavasqlitercustom.so and all dependencies seem to be present in libs.

Also a question to the team: are there plans to resurrect this task and include arm support in official release?

**Comment by d122y** [comment]
The issue appeared to be in GLIBCXX being an older version on the target board than libcbljavasqlitecustom.so required. Found that out after I added some logging in the catch block of com.couchbase.lite.storage.SQLiteNativeLibrary.load method
